version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Melbourne"
    labels:
      - "automerge"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Australia/Melbourne"
    labels:
      - "automerge"
