name: README Stars
on:
  schedule:
    - cron: "51 */4 * 12 *"  # Every 4 hours in December
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1573050
          leaderboardId: 1573050
          sessionCookie: ${{ secrets.AOC_SESSION }}

      - run: |
          sed -i '/\[Day [0-9]*\](https:\/\/adventofcode.com\/[0-9]*\/day\/[0-9]*)/!b; s|\[Day \([0-9]*\)\](https:\/\/adventofcode.com\/\([0-9]*\)\/day\/[0-9]*)|\[Day \1](\2/\1/README.md) | ⭐ [Solution](\2/\1/01.go) | ⭐ [Solution](\2/\1/02.go)|' README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
