name: README Stars
on:
  schedule:
    - cron: "51 */4 * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1573050
          leaderboardId: 1573050
          sessionCookie: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars

  update-readme-2021:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1573050
          leaderboardId: 1573050
          sessionCookie: ${{ secrets.AOC_SESSION }}
          tableMarker: "<!--- advent_readme_stars_2021 table --->"
          year: 2021
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars

  update-readme-2020:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1573050
          leaderboardId: 1573050
          sessionCookie: ${{ secrets.AOC_SESSION }}
          tableMarker: "<!--- advent_readme_stars_2020 table --->"
          year: 2020
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars