name: README Stars
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 */4 * 12 *
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1573050
          leaderboardId: 1573050
          sessionCookie: ${{ secrets.AOC_SESSION }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README stars
