name: README Stars
on:
  schedule:
    - cron: "51 */4 * 12 *"  # Every 4 hours in December
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1573050
          leaderboardId: 1573050
          sessionCookie: ${{ secrets.AOC_SESSION }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
